# No Response
#
# Close issues that don't have enough information to be actionable.
#
# References:
#
# - https://docs.github.com/actions/using-workflows/events-that-trigger-workflows#issue_comment
# - https://docs.github.com/actions/using-workflows/events-that-trigger-workflows#schedule
# - https://docs.github.com/webhooks-and-events/webhooks/webhook-events-and-payloads#issue_comment
# - https://github.com/lee-dohm/no-response

---
name: no-response
on:
  issue_comment:
    types:
      - created
  schedule:
    # five minutes after the hour, every hour
    - cron: 5 * * * *
permissions:
  issues: write
jobs:
  no-response:
    runs-on: ubuntu-latest
    steps:
      - id: close-issues
        name: Closes issues missing actionable info
        uses: lee-dohm/no-response@v0.5.0
        with:
          closeComment: |
            This issue has been automatically closed because there has been no response to our
            request for more information from the original author. With only the information that is
            currently available, there isn't enough information to take action. Please reach out if
            you have or find the answers needed so next steps, if any, can be determined.
          daysUntilClose: 14
          responseRequiredLabel: status:awaiting-answers
          token: ${{ secrets.GITHUB_TOKEN }}
